import Script from "next/script";
import Image from "next/image";
import { Header } from "@/components/Header";
import { BrandLogo } from "@/components/BrandLogo";
import { Hero } from "@/components/Hero";
import { Services } from "@/components/Services";
import { VideoGuestbook } from "@/components/VideoGuestbook";
import { Portfolio } from "@/components/Portfolio";
import { ContactForm } from "@/components/ContactForm";
import { Reveal } from "@/components/Reveal";

const schema={"@context":"https://schema.org","@graph":[{"@type":["LocalBusiness","EventPlanner"],"@id":"https://popnbloomevents.ca/#business",name:"Pop'n Bloom Events",url:"https://popnbloomevents.ca/",logo:"https://popnbloomevents.ca/popnbloom-logo.png",image:"https://popnbloomevents.ca/images/hero-mirae-turns-one.jpg",telephone:"+1-236-869-5203",priceRange:"$$",address:{"@type":"PostalAddress",addressLocality:"Metro Vancouver",addressRegion:"BC",addressCountry:"CA"},areaServed:["Vancouver","Burnaby","Richmond","Surrey","Coquitlam","New Westminster","Delta","Langley"],description:"Metro Vancouver event styling studio specializing in custom balloon décor, event backdrops and vintage video guestbook rentals.",knowsAbout:["Balloon garlands","Birthday party decorations","Custom event backdrops","Baptism decorations","Video guestbook rentals"]},{"@type":"WebSite","@id":"https://popnbloomevents.ca/#website",url:"https://popnbloomevents.ca/",name:"Pop'n Bloom Events",publisher:{"@id":"https://popnbloomevents.ca/#business"},inLanguage:"en-CA"},{"@type":"ItemList",name:"Event styling services",itemListElement:[{"@type":"Service",position:1,name:"Balloon Décor and Event Backdrops",provider:{"@id":"https://popnbloomevents.ca/#business"},areaServed:"Metro Vancouver, BC",description:"Custom organic balloon garlands, arches, statement columns, personalized panels, florals, props and complete backdrop styling."},{"@type":"Service",position:2,name:"Vintage Video Guestbook Rental",provider:{"@id":"https://popnbloomevents.ca/#business"},areaServed:"Metro Vancouver, BC",description:"A decorated vintage telephone video guestbook experience that records heartfelt guest messages for birthdays, weddings and milestone events."}]}]};

export default function Home(){return <><Script id="local-business-schema" type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Header/><main><Hero/><Services/><VideoGuestbook/><Portfolio/>
<section className="inspiration section" id="inspiration"><Reveal className="container inspiration-grid"><div className="inspiration-copy"><p className="eyebrow light">Your idea, our creative touch</p><h2>Start with an inspiration.<br/><span>We’ll help make it yours.</span></h2><p>You don’t need to know exactly what to order. Send us a photo, a theme, a colour palette, or even just your budget. We’ll recommend a setup that makes sense for your celebration.</p><a className="button button-cream" href="#contact">Tell Us Your Idea</a></div><div className="collage" aria-label="A collage of Pop'n Bloom event designs"><div className="collage-main"><Image unoptimized src="/images/kpop-demon-hunters-2.png" alt="Purple, gold and pink themed birthday backdrop" fill sizes="(max-width:800px) 65vw,30vw"/></div><div><Image unoptimized src="/images/mirae-dessert-table-detail.jpg" alt="First birthday dessert table detail" fill sizes="(max-width:800px) 35vw,15vw"/></div><div><Image unoptimized src="/images/princess-7-indoor.jpg" alt="Princess-themed balloon display" fill sizes="(max-width:800px) 35vw,15vw"/></div></div></Reveal></section>
<section className="about section" id="about"><Reveal className="container about-grid"><div className="about-image"><Image unoptimized src="/images/video-guestbook-floral.jpg" alt="Pop'n Bloom floral video guestbook installation" fill sizes="(max-width:800px) 100vw,48vw"/></div><div className="about-copy"><p className="eyebrow">About Pop’n Bloom Events</p><h2>Celebrations should feel<br/><span>like the people in them.</span></h2><p><strong>Pop’n Bloom Events is a Metro Vancouver event styling studio creating balloon décor, personalized backdrops, and memory-focused experiences for life’s special moments.</strong></p><p>We love making events feel polished, warm, and personal—whether you’re planning a child’s birthday, baptism, graduation, milestone birthday, intimate celebration, or corporate event.</p><div className="chips">{["Birthdays","Baptisms","Baby Showers","Graduations","Milestones","Corporate"].map(x=><span key={x}>{x}</span>)}</div></div></Reveal></section>
<section className="contact section" id="contact"><Reveal className="container contact-grid"><div className="contact-copy"><p className="eyebrow">Let’s create something beautiful</p><h2>Tell us what you’re<br/><span>celebrating.</span></h2><p>Share your date, location, inspiration, colours, and approximate budget. We’ll help you build the right setup for your day.</p><address><strong>Metro Vancouver, BC</strong><a href="tel:+12368695203">236 869 5203</a><a href="https://www.popnbloomevents.ca">www.popnbloomevents.ca</a></address></div><ContactForm/></Reveal></section></main>
<footer><div className="container footer-inner"><BrandLogo/><p>Creating celebrations that pop &amp; bloom.</p><div className="footer-links"><a href="tel:+12368695203">236 869 5203</a><a href="#" aria-label="Instagram placeholder">Instagram</a><a href="#" aria-label="Facebook placeholder">Facebook</a></div><small>© {new Date().getFullYear()} Pop’n Bloom Events · Metro Vancouver, BC</small><a className="ae-credit" href="https://aedigitalstudio.ca" target="_blank" rel="noopener noreferrer" aria-label="Website powered by AE Digital Studio"><span className="ae-mark">AE</span><span>Powered by <strong>AE Digital Studio</strong></span></a></div></footer></>}
